project_name: golab
before:
  hooks:
    - go mod tidy
brews:
  -
    description: "A command-line tool for gitlab"
    homepage: "https://github.com/cloudingcity/golab"
    github:
      owner: cloudingcity
      name: homebrew-tap
    dependencies:
    - git
    install: |
      bin.install "golab"
builds:
  - goos:
      - linux
      - darwin
      - windows
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
