// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gitlab "github.com/xanzy/go-gitlab"
)

// GitlabValidateService is an autogenerated mock type for the GitlabValidateService type
type GitlabValidateService struct {
	mock.Mock
}

// Lint provides a mock function with given fields: content, options
func (_m *GitlabValidateService) Lint(content string, options ...gitlab.OptionFunc) (*gitlab.LintResult, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, content)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gitlab.LintResult
	if rf, ok := ret.Get(0).(func(string, ...gitlab.OptionFunc) *gitlab.LintResult); ok {
		r0 = rf(content, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.LintResult)
		}
	}

	var r1 *gitlab.Response
	if rf, ok := ret.Get(1).(func(string, ...gitlab.OptionFunc) *gitlab.Response); ok {
		r1 = rf(content, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, ...gitlab.OptionFunc) error); ok {
		r2 = rf(content, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
