// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gitlab "github.com/xanzy/go-gitlab"
)

// GitlabSearchService is an autogenerated mock type for the GitlabSearchService type
type GitlabSearchService struct {
	mock.Mock
}

// MergeRequestsByProject provides a mock function with given fields: pid, query, opt, options
func (_m *GitlabSearchService) MergeRequestsByProject(pid interface{}, query string, opt *gitlab.SearchOptions, options ...gitlab.OptionFunc) ([]*gitlab.MergeRequest, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, query, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*gitlab.MergeRequest
	if rf, ok := ret.Get(0).(func(interface{}, string, *gitlab.SearchOptions, ...gitlab.OptionFunc) []*gitlab.MergeRequest); ok {
		r0 = rf(pid, query, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.MergeRequest)
		}
	}

	var r1 *gitlab.Response
	if rf, ok := ret.Get(1).(func(interface{}, string, *gitlab.SearchOptions, ...gitlab.OptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, query, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(interface{}, string, *gitlab.SearchOptions, ...gitlab.OptionFunc) error); ok {
		r2 = rf(pid, query, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
